#
# GROUPS
#
- id: nsdb
  parameters:
    strategy:
      type: parallel
  requires:
  - deploy_start
  required_for:
  - controller
  - primary-controller
  - deploy_end
  role:
  - nsdb
  type: group
  tasks:
  - logging
  - hiera
  - globals
  - netconfig

# Override neutron params
- id: install_common_deps
  role:
  - primary-controller
  - controller
  - compute
  - nsdb
  - midonet-gw
  - midonet-analytics
  type: shell
  requires: [pre_deployment_start]
  required_for: [pre_deployment_end]
  version: 2.0.0
  parameters:
    cmd: bash install_midonet_common_modules_and_gems.sh
    timeout: 1440

- id: override_neutron_module
  role:
  - primary-controller
  - controller
  - compute
  - nsdb
  - midonet-gw
  - midonet-analytics
  type: shell
  requires: [pre_deployment_start]
  required_for: [pre_deployment_end]
  version: 2.0.0
  parameters:
    cmd: bash override_neutron_module.sh
    timeout: 1440

# Override neutron params
- id: neutron-override
  role:
  - primary-controller
  - controller
  - compute
  - nsdb
  - midonet-gw
  - midonet-analytics
  type: puppet
  requires: [pre_deployment_start]
  required_for: [pre_deployment_end]
  version: 2.0.0
  parameters:
    puppet_manifest: puppet/manifests/midonet-override-hiera.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 1440

# Install the MidoNet Package. Everywhere
- id: install_midonet_package
  role:
  - primary-controller
  - controller
  - compute
  - nsdb
  - midonet-gw
  - midonet-analytics
  type: shell
  requires: [deploy_start,setup_repositories]
  required_for: [fuel_pkgs]
  version: 2.0.0
  parameters:
    cmd: bash install_midonet_package_from_source.sh
    timeout: 1440

# Install the MidoNet_Openstack Package where needed. For Java, Zookeeper and Cassandra
- id: install_midonet_openstack_package
  role:
  - primary-controller
  - controller
  - compute
  - nsdb
  - midonet-gw
  - midonet-analytics
  type: shell
  requires: [deploy_start,setup_repositories]
  required_for: [fuel_pkgs]
  version: 2.0.0
  parameters:
    cmd: bash install_midonet_openstack_package.sh
    timeout: 1440


# First independent tasks
- id: setup_repositories_midonet
  groups:
  - primary-controller
  - controller
  - compute
  - nsdb
  required_for:
  - deploy_end
  requires:
  - netconfig
  - install_common_deps
  - install_midonet_package
  - install_midonet_openstack_package
  - override_neutron_module
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/midonet-define-repositories.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 1440

- id: enable_ip_forward_midonet
  groups:
  - compute
  - controller
  - primary-controller
  required_for:
  - deploy_end
  requires:
  - deploy_start
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/midonet-enable-ip-forward.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 720


# PRE-NEUTRON CONFIGURATION
- id: deploy_cluster_midonet
  groups:
  - primary-controller
  - controller
  required_for:
  - deploy_end
  - openstack-network-start
  requires:
  - setup_repositories_midonet
  - enable_ip_forward_midonet
  - firewall
  - primary-cluster-haproxy
  - cluster-haproxy
  type: puppet
  reexecute_on:
  - deploy_changes
  parameters:
    puppet_manifest: puppet/manifests/midonet-install-cluster.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 1440

# In controllers, we have to install midolman 'before' the neutron
# configuration, because subnet creates a the DHCP port in neutron
# and we need to do the binding.
- id: agent-midonet-controller
  groups:
  - primary-controller
  - controller
  required_for:
  - deploy_end
  - openstack-network-start
  requires:
  - deploy_cluster_midonet
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/midonet-install-agent.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 1440

# NEUTRON CONFIGURATION
- id: openstack-network-midonet-replace-service-name
  groups:
  - primary-controller
  - controller
  requires:
  - openstack-network-common-config
  required_for:
  - openstack-network-end
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/midonet-replace-guess-func.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 1440

- id: openstack-network-midonet-config
  groups:
  - primary-controller
  - controller
  requires:
  - openstack-network-midonet-replace-service-name
  - setup_repositories_midonet
  required_for:
  - openstack-network-server-config
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/midonet-neutron-configure.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 1440

- id: openstack-network-midonet-networks
  groups:
  - primary-controller
  requires:
  - openstack-network-server-config
  - openstack-network-midonet-config
  - setup_repositories_midonet
  required_for:
  - openstack-network-end
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/midonet-neutron-networks.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 1440

- id: openstack-network-midonet-edge
  groups:
  - primary-controller
  requires:
  - openstack-network-server-config
  - openstack-network-midonet-config
  - setup_repositories_midonet
  - openstack-network-midonet-networks
  required_for:
  - openstack-network-end
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/midonet-edge-router-setup.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 1440

- id: openstack-network-midonet-edge-bgp
  groups:
  - primary-controller
  requires:
  - openstack-network-server-config
  - openstack-network-midonet-config
  - setup_repositories_midonet
  - openstack-network-midonet-networks
  - openstack-network-midonet-edge
  required_for:
  - openstack-network-end
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/midonet-edge-router-setup-bgp.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 1440
  condition:
    yaql_exp: "$.midonet.gateway_type = 'bgp'"

- id: openstack-network-midonet-edge-static
  groups:
  - primary-controller
  requires:
  - openstack-network-server-config
  - openstack-network-midonet-config
  - setup_repositories_midonet
  - openstack-network-midonet-networks
  - openstack-network-midonet-edge
  required_for:
  - openstack-network-end
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/midonet-edge-router-setup-static.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 1440
  condition:
    yaql_exp: "$.midonet.gateway_type = 'static'"

- id: openstack-network-midonet-gatway-static
  groups:
  - primary-controller
  requires:
  - openstack-network-server-config
  - openstack-network-midonet-config
  - setup_repositories_midonet
  - openstack-network-midonet-networks
  - openstack-network-midonet-edge
  - openstack-network-midonet-edge-static
  required_for:
  - openstack-network-end
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/midonet-gateway-static.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 1440
  condition:
    yaql_exp: "$.midonet.gateway_type = 'static'"

- id: openstack-network-midonet-compute-nova
  parameters:
    puppet_manifest: puppet/manifests/midonet-compute-nova.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 1440
  required_for:
  - openstack-network-end
  requires:
  - setup_repositories_midonet
  - openstack-network-common-config
  - openstack-network-agents-l3
  - openstack-network-agents-metadata
  type: puppet
  groups:
  - compute

# NSDB-only tasks
- id: zookeeper_and_cassandra_midonet
  groups:
  - nsdb
  required_for:
  - deploy_end
  requires:
  - deploy_start
  - install_midonet_openstack_package
  - install_midonet_package
  - netconfig
  type: puppet
  reexecute_on:
  - deploy_changes
  parameters:
    puppet_manifest: puppet/manifests/midonet-nsdb.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 1440


# Skipped tasks
- id: openstack-network-server-config
  type: skipped
- id: openstack-network-networks
  type: skipped
- id: openstack-network-routers
  type: skipped
- id: openstack-network-plugins-l2
  type: skipped
- id: primary-openstack-network-plugins-l2
  type: skipped
- id: openstack-network-agents-l3
  type: skipped
- id: primary-openstack-network-agents-l3
  type: skipped
- id: openstack-network-compute-nova
  type: skipped
  # This task tries to enable the service nova_compute but we already to that
  # inside our custom midonet-compute-nova task.
- id: enable_nova_compute_service
  type: skipped


# POST-DEPLOYMENT TASKS

# The task configure_default_route reinstalls openvswitch-switch
# and removes midolman. This task only runs on compute hosts, so
# we have to make sure that midolman is installed 'after' the
# 'configure_default_route' task has run
- id: agent-midonet-compute
  role:
  - compute
  required_for:
  - post_deployment_end
  requires:
  - configure_default_route
  - post_deployment_start
  type: puppet
  reexecute_on:
  - deploy_changes
  parameters:
    puppet_manifest: puppet/manifests/midonet-install-agent.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 1440

- id: tunnel-zones-midonet
  role:
  - compute
  - controller
  - primary-controller
  required_for:
  - post_deployment_end
  requires:
  - post_deployment_start
  - agent-midonet-compute
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/midonet-host-registry.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 720

- id: rootwrap-midonet
  role:
  - compute
  - controller
  - primary-controller
  required_for:
  - post_deployment_end
  requires:
  - post_deployment_start
  - agent-midonet-compute
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/midonet-ensure-rootwrap.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 720
