#
# GROUPS
#
- id: nsdb
  parameters:
    strategy:
      type: parallel
  requires:
  - deploy_start
  required_for:
  - controller
  - primary-controller
  - deploy_end
  role:
  - nsdb
  type: group
  tasks:
  - logging
  - hiera
  - globals
  - netconfig


# Override neutron params
- id: install_common_deps
  role:
  - primary-controller
  - controller
  - compute
  - nsdb
  - midonet-gw
  - midonet-analytics
  type: shell
  requires: [pre_deployment_start]
  required_for: [pre_deployment_end]
  version: 2.0.0
  parameters:
    cmd: bash install_midonet_common_modules_and_gems.sh
    timeout: 1440

# Override neutron params
- id: neutron-override
  role:
  - primary-controller
  - controller
  - compute
  - nsdb
  - midonet-gw
  - midonet-analytics
  type: puppet
  requires: [pre_deployment_start]
  required_for: [pre_deployment_end]
  version: 2.0.0
  parameters:
    puppet_manifest: puppet/manifests/midonet-override-hiera.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 1440

# Install the MidoNet Package. Everywhere
- id: install_midonet_package
  role:
  - primary-controller
  - controller
  - compute
  - nsdb
  - midonet-gw
  - midonet-analytics
  type: shell
  requires: [deploy_start,setup_repositories]
  required_for: [fuel_pkgs]
  version: 2.0.0
  parameters:
    cmd: bash install_midonet_package_from_source.sh
    timeout: 1440

# Install the MidoNet_Openstack Package where needed. For Java, Zookeeper and Cassandra
- id: install_midonet_openstack_package
  role:
  - primary-controller
  - controller
  - compute
  - nsdb
  - midonet-gw
  - midonet-analytics
  type: shell
  requires: [deploy_start,setup_repositories]
  required_for: [fuel_pkgs]
  version: 2.0.0
  parameters:
    cmd: bash install_midonet_openstack_package.sh
    timeout: 1440

# NSDB-only tasks
- id: zookeeper_and_cassandra_midonet
  groups:
  - nsdb
  required_for:
  - deploy_end
  requires:
  - deploy_start
  - install_midonet_openstack_package
  - install_midonet_package
  - netconfig
  type: puppet
  reexecute_on:
  - deploy_changes
  parameters:
    puppet_manifest: puppet/manifests/midonet-nsdb.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 1440


# Skipped tasks
- id: openstack-network-server-config
  type: skipped
- id: openstack-network-networks
  type: skipped
- id: openstack-network-routers
  type: skipped
- id: openstack-network-plugins-l2
  type: skipped
- id: primary-openstack-network-plugins-l2
  type: skipped
- id: openstack-network-agents-l3
  type: skipped
- id: primary-openstack-network-agents-l3
  type: skipped
- id: openstack-network-compute-nova
  type: skipped
